// Part 1: Dot-Com Crash, Early Search Engines, Web 1.0 Portals, Google Graveyard, Microsoft, Yahoo, Apple, AOL Relics
export const DATA_PART_1 = [
  // --- DOT-COM & EARLY SEARCH ENGINES ---
  {
    name: "Excite",
    slug: "excite",
    domain: "excite.com",
    category: "Search",
    status: "ZOMBIE",
    founded_year: 1995,
    death_year: 2001,
    cause_category: "Market Competition",
    tagline: "One of the most recognized 1990s web portals that famously declined to buy Google for $750,000.",
    description: "Excite was founded in 1995 by six Stanford students and grew into one of the largest web portals of the 1990s. In 1999, Sergey Brin and Larry Page offered to sell Google to Excite CEO George Bell for $750,000; Bell rejected the offer. Excite merged with broadband provider @Home in a disastrous $6.7B deal and filed for bankruptcy in 2001.",
    cause_summary: "Disastrous @Home merger debt, declining search market share against Yahoo and Google, and rejection of the $750k Google acquisition.",
    final_moments: "Filed for Chapter 11 bankruptcy in October 2001. Assets sold to InfoSpace for a fraction of its former valuation.",
    parent_company: "Excite@Home",
    country: "United States",
    peak_users: "20 Million MAU"
  },
  {
    name: "WebCrawler",
    slug: "webcrawler",
    domain: "webcrawler.com",
    category: "Search",
    status: "ZOMBIE",
    founded_year: 1994,
    death_year: 2001,
    cause_category: "Acquired & Discontinued",
    tagline: "The very first search engine to provide full-text search across web pages.",
    description: "Created by Brian Pinkerton at the University of Washington on January 27, 1994, WebCrawler was the first Web search engine to index entire page contents. It was acquired by AOL in 1995, then sold to Excite in 1997, and eventually became a generic meta-search aggregator.",
    cause_summary: "Acquired repeatedly by AOL and Excite; its core spidering technology was abandoned in favor of meta-search syndication.",
    final_moments: "Sold off in the Excite@Home bankruptcy auction in 2001 to InfoSpace.",
    parent_company: "AOL / Excite",
    country: "United States",
    peak_users: "15 Million Monthly Queries"
  },
  {
    name: "Lycos Classic",
    slug: "lycos-classic",
    domain: "lycos.com",
    category: "Search",
    status: "ZOMBIE",
    founded_year: 1994,
    death_year: 2004,
    cause_category: "Market Competition",
    tagline: "The black retriever portal that guided millions through the early web with 'Go Get It!'",
    description: "Developed at Carnegie Mellon University in 1994 by Michael Loren Mauldin, Lycos became the most visited online destination in the world in 1999. Spanish telecoms giant Terra Networks bought it for $12.5 billion in 2000 at the peak of the dot-com bubble, before selling it in 2004 for only $95 million.",
    cause_summary: "Dot-com crash burst its $12.5B valuation; Terra Networks failed to integrate it before fire-selling to Daum Communications in South Korea.",
    final_moments: "Sold to Daum in 2004 for less than 1% of its dot-com peak valuation.",
    parent_company: "Terra Lycos",
    country: "United States",
    peak_users: "32 Million Visitors"
  },
  {
    name: "InfoSeek",
    slug: "infoseek",
    domain: "infoseek.com",
    category: "Search",
    status: "CONFIRMED_DEAD",
    founded_year: 1994,
    death_year: 2001,
    cause_category: "Acquired & Discontinued",
    tagline: "The default search engine bundled with Netscape Navigator 1.0.",
    description: "Founded by Steve Kirsch in 1994, InfoSeek became popular when Netscape made it the default search engine in early versions of Navigator. In 1998, Disney acquired a 43% stake and merged it into the Go.com portal, taking a catastrophic $790M write-off when it closed the search engine in 2001.",
    cause_summary: "Swallowed by Disney's disastrous Go.com portal strategy; shut down following massive multi-hundred-million-dollar write-downs.",
    final_moments: "Disney pulled the plug on the Go.com search engine in January 2001, laying off thousands of staff.",
    parent_company: "The Walt Disney Company",
    country: "United States",
    peak_users: "18 Million Users"
  },
  {
    name: "HotBot",
    slug: "hotbot",
    domain: "hotbot.com",
    category: "Search",
    status: "ZOMBIE",
    founded_year: 1996,
    death_year: 2002,
    cause_category: "Market Competition",
    tagline: "Wired magazine's neon-colored search engine powered by Inktomi.",
    description: "HotBot was launched in May 1996 by Wired Magazine. Known for its retro-futuristic neon interface and rapid Inktomi indexing engine, it was considered one of the fastest search engines of the mid-90s before being acquired by Lycos and left to wither.",
    cause_summary: "Acquired by Lycos in 1998; lost its technical edge as Inktomi and Lycos fell behind Google's PageRank crawler.",
    final_moments: "Relegated to a rebranded multi-search aggregator in 2002, losing its original crawler engine.",
    parent_company: "Lycos / Wired Ventures",
    country: "United States",
    peak_users: "10 Million Visitors"
  },
  {
    name: "AllTheWeb",
    slug: "alltheweb",
    domain: "alltheweb.com",
    category: "Search",
    status: "CONFIRMED_DEAD",
    founded_year: 1999,
    death_year: 2011,
    cause_category: "Acquired & Discontinued",
    tagline: "FAST's Norwegian indexing giant that rivaled Google in index size and speed.",
    description: "AllTheWeb was created in 1999 by Fast Search & Transfer (FAST) in Trondheim, Norway. It was Google's fiercest rival in pure search index size and speed during the early 2000s. Overture acquired it in 2003, Yahoo acquired Overture, and Yahoo shut it down in April 2011.",
    cause_summary: "Acquired by Yahoo via Overture; Yahoo dismantled FAST's search infrastructure to standardize on internal Yahoo Search.",
    final_moments: "On April 4, 2011, Yahoo permanently redirected alltheweb.com to yahoo.com, shutting down 12 years of history.",
    parent_company: "Yahoo! / Fast Search & Transfer",
    country: "Norway",
    peak_users: "15 Million Monthly Users"
  },
  {
    name: "Inktomi",
    slug: "inktomi",
    domain: "inktomi.com",
    category: "Search",
    status: "CONFIRMED_DEAD",
    founded_year: 1996,
    death_year: 2003,
    cause_category: "Acquired & Discontinued",
    tagline: "The backend algorithmic search engine that powered HotBot, Yahoo, and MSN.",
    description: "Founded by UC Berkeley professor Eric Brewer and graduate student Paul Gauthier, Inktomi built the backend search cluster technology used by Yahoo!, MSN, and HotBot. At its peak in March 2000, Inktomi stock was valued at $25 billion; Yahoo bought the entire company in 2003 for just $235 million.",
    cause_summary: "Collapse of wholesale search provider economics as portals built internal search or switched to Google.",
    final_moments: "Acquisition by Yahoo finalized in March 2003; its brand and infrastructure were folded into Yahoo Search.",
    parent_company: "Yahoo!",
    country: "United States",
    peak_users: "Backend for 50M+ Web Searches"
  },
  {
    name: "Dogpile Classic",
    slug: "dogpile-classic",
    domain: "dogpile.com",
    category: "Search",
    status: "ZOMBIE",
    founded_year: 1996,
    death_year: 2007,
    cause_category: "Technological Obsolescence",
    tagline: "The friendly hound that fetched results simultaneously from every major search engine.",
    description: "Created by Aaron Flin in November 1996, Dogpile aggregated results from Yahoo!, Google, AltaVista, Lycos, and Excite into a single page. It became popular because no single 90s search engine had full coverage of the web. As Google's index approached near-total coverage, meta-search lost its primary value proposition.",
    cause_summary: "Direct single-crawler engines (Google) outgrew the need for multi-engine meta-search aggregators.",
    final_moments: "InfoSpace acquired Dogpile and turned it into an advertising syndicated link farm.",
    parent_company: "InfoSpace / Blucora",
    country: "United States",
    peak_users: "12 Million Users"
  },
  {
    name: "Northern Light",
    slug: "northern-light",
    domain: "northernlight.com",
    category: "Search",
    status: "CONFIRMED_DEAD",
    founded_year: 1997,
    death_year: 2002,
    cause_category: "Strategic Pivot",
    tagline: "The search engine with dynamic custom folders and a pay-per-article research vault.",
    description: "Northern Light launched in August 1997 with a unique categorization engine that grouped search results into dynamic hierarchical folders. It also indexed full-text articles from premium periodicals for $1 to $4 each. In January 2002, Northern Light abruptly shut down its public web search engine to pivot exclusively to enterprise business intelligence.",
    cause_summary: "Public consumer search monetization failed; pivoted completely to enterprise competitive intelligence.",
    final_moments: "Shut down public search in January 2002, leaving thousands of researchers stranded without the custom folder index.",
    parent_company: "Northern Light Group",
    country: "United States",
    peak_users: "5 Million Monthly Researchers"
  },
  {
    name: "Go.com Portal",
    slug: "go-com",
    domain: "go.com",
    category: "Search",
    status: "CONFIRMED_DEAD",
    founded_year: 1998,
    death_year: 2001,
    cause_category: "Strategic Pivot",
    tagline: "Disney's multi-billion-dollar green traffic light portal disaster.",
    description: "Go.com was a massive web portal created in 1998 by The Walt Disney Company combining Disney.com, ABCNEWS.com, ESPN.com, and InfoSeek. Despite intensive prime-time television advertising and the iconic green stoplight logo, Go.com failed to compete with Yahoo and AOL, costing Disney nearly $1 billion in losses.",
    cause_summary: "Over-centralized corporate portal design, lack of focus, and catastrophic drop in digital advertising post-dot-com bubble.",
    final_moments: "Disney shut down Go.com as an independent portal in January 2001, taking an enormous $790 million charge.",
    parent_company: "The Walt Disney Company",
    country: "United States",
    peak_users: "25 Million Monthly Visitors"
  },
  // --- DOT-COM CRASH E-COMMERCE CASUALTIES ---
  {
    name: "Kozmo.com",
    slug: "kozmo",
    domain: "kozmo.com",
    category: "Web technology",
    status: "CONFIRMED_DEAD",
    founded_year: 1998,
    death_year: 2001,
    cause_category: "Bankruptcy",
    tagline: "Free 1-hour courier delivery for a single DVD or pack of gum.",
    description: "Founded by young investment bankers Joseph Park and Yong Kang, Kozmo.com promised free 1-hour delivery of movies, snacks, ice cream, electronics, and magazines in major US cities by bicycle couriers wearing orange messenger bags. With zero delivery minimums, delivering a $1.50 candy bar cost Kozmo more than $10 in courier expenses.",
    cause_summary: "Per-unit economic impossibility; burning $280M of venture capital offering free delivery without minimum orders.",
    final_moments: "Ceased operations abruptly in April 2001, laying off all 1,100 couriers and warehouse workers.",
    parent_company: "Kozmo Inc.",
    country: "United States",
    peak_users: "Hundreds of thousands in NYC, SF, Boston"
  },
  {
    name: "Webvan",
    slug: "webvan",
    domain: "webvan.com",
    category: "Web technology",
    status: "CONFIRMED_DEAD",
    founded_year: 1996,
    death_year: 2001,
    cause_category: "Bankruptcy",
    tagline: "The $1 billion robotic automated grocery delivery catastrophe.",
    description: "Founded by Louis Borders, Webvan was an online grocery business that built $30 million automated robotic warehouses before proving consumer demand in any single market. After raising $375M in an IPO and burning over $800M in venture funds, it filed for bankruptcy in July 2001.",
    cause_summary: "Premature scaling: committing $1B to build 26 high-tech robotic distribution centers before establishing regional profitability.",
    final_moments: "Filed Chapter 11 bankruptcy in July 2001, laying off 2,000 employees and auctioning off vans.",
    parent_company: "Webvan Group Inc.",
    country: "United States",
    peak_users: "750,000 Customers"
  },
  {
    name: "eToys.com",
    slug: "etoys",
    domain: "etoys.com",
    category: "Web technology",
    status: "CONFIRMED_DEAD",
    founded_year: 1997,
    death_year: 2001,
    cause_category: "Bankruptcy",
    tagline: "The dot-com toy retailer whose market cap briefly eclipsed Toys 'R' Us.",
    description: "eToys.com launched in 1997 and went public in May 1999, surging to an $8 billion valuation that exceeded traditional retail giant Toys 'R' Us despite having minimal revenue. Disastrous fulfillment failures during the 1999 Christmas holiday season ruined consumer trust.",
    cause_summary: "Warehouse fulfillment chaos during the 1999 holiday rush, unsustainable ad burn, and the total collapse of tech stock liquidity.",
    final_moments: "Closed operations in February 2001 and filed for Chapter 11 in March 2001.",
    parent_company: "eToys Inc.",
    country: "United States",
    peak_users: "5 Million Holiday Shoppers"
  },
  {
    name: "Boo.com",
    slug: "boo-com",
    domain: "boo.com",
    category: "Web technology",
    status: "CONFIRMED_DEAD",
    founded_year: 1998,
    death_year: 2000,
    cause_category: "Bankruptcy",
    tagline: "Burned $135 million in 18 months trying to sell designer sportswear over dial-up connections.",
    description: "Boo.com was a British online fashion retailer founded by Ernst Malmsten and Kajsa Leander. It launched simultaneously in 18 countries with high-resolution 3D rotating mannequins and synthetic digital assistant 'Miss Boo' that completely froze 56k dial-up modems.",
    cause_summary: "Burned $135M in 18 months on global launch marketing while its Flash/JavaScript 3D mannequins crashed consumer computers.",
    final_moments: "Placed into receivership on May 18, 2000, becoming the quintessential symbol of European dot-com hubris.",
    parent_company: "Boo.com Group",
    country: "United Kingdom / Sweden",
    peak_users: "Over-hyped 100k visitors"
  },
  {
    name: "Flooz.com",
    slug: "flooz",
    domain: "flooz.com",
    category: "Web technology",
    status: "CONFIRMED_DEAD",
    founded_year: 1998,
    death_year: 2001,
    cause_category: "Bankruptcy",
    tagline: "The synthetic digital currency endorsed by Whoopi Goldberg that Russian syndicates plundered.",
    description: "Flooz was an early attempt at private online currency promoted with expensive national TV ad campaigns starring Whoopi Goldberg. Customers purchased Flooz credits to spend at merchant partners. In 2001, the FBI informed Flooz that a Russian organized crime syndicate had systematically laundered millions using stolen credit cards.",
    cause_summary: "Massive credit card fraud by Russian cybercrime syndicates and lack of consumer adoption of private merchant currencies.",
    final_moments: "Forced to shutter abruptly in August 2001 after merchant chargebacks wiped out all remaining cash reserves.",
    parent_company: "Flooz.com Inc.",
    country: "United States",
    peak_users: "1 Million Registered Accounts"
  },
  {
    name: "Beenz.com",
    slug: "beenz",
    domain: "beenz.com",
    category: "Web technology",
    status: "CONFIRMED_DEAD",
    founded_year: 1998,
    death_year: 2001,
    cause_category: "Bankruptcy",
    tagline: "The web's original micropayment loyalty currency: 'The web's currency'.",
    description: "Beenz was an online rewards currency founded in the UK where users earned 'beenz' by visiting websites, filling surveys, and shopping. Central banks in Europe even investigated whether Beenz was trying to create an unregulated global fiat currency before its business model collapsed in the dot-com bust.",
    cause_summary: "High transaction processing overhead, limited merchant utility, and regulatory friction across central banks.",
    final_moments: "Terminated consumer accounts on August 17, 2001, settling accounts for pennies on the dollar.",
    parent_company: "The Beenz.com Company",
    country: "United Kingdom",
    peak_users: "5 Million Accounts"
  },
  {
    name: "Urbanfetch",
    slug: "urbanfetch",
    domain: "urbanfetch.com",
    category: "Web technology",
    status: "CONFIRMED_DEAD",
    founded_year: 1999,
    death_year: 2000,
    cause_category: "Bankruptcy",
    tagline: "Kozmo's stylish New York rival promising free 1-hour delivery of DVDs and sushi.",
    description: "Urbanfetch competed head-to-head with Kozmo in Manhattan and London, operating fleets of vans and couriers delivering entertainment, electronics, and gourmet food within an hour. Founded by Ross Stevens, it burned tens of millions in marketing before capital dried up.",
    cause_summary: "Unsustainable unit delivery economics, zero delivery fees, and venture capital withdrawal in late 2000.",
    final_moments: "Shut down consumer delivery service in October 2000, attempting an unsuccessful pivot to B2B courier logistics.",
    parent_company: "Urbanfetch Inc.",
    country: "United States",
    peak_users: "100,000 New Yorkers"
  },
  {
    name: "TheGlobe.com",
    slug: "theglobe-com",
    domain: "theglobe.com",
    category: "Social",
    status: "CONFIRMED_DEAD",
    founded_year: 1994,
    death_year: 2008,
    cause_category: "Bankruptcy",
    tagline: "The Cornell dorm-room community whose IPO skyrocketed 606% on its first day in 1998.",
    description: "Founded in 1994 by Cornell undergraduate students Stephan Paternot and Todd Krizelman, theGlobe.com was one of the earliest social networking communities. On November 13, 1998, its IPO set the all-time Wall Street record for first-day percentage gain, rising 606% from $9 to $97 per share.",
    cause_summary: "Stock plummeted 99% when advertising revenues dried up; co-founders resigned as it devolved into a shell company.",
    final_moments: "Shut down operations in 2008 after lawsuits stemming from VoIP spam domain acquisitions.",
    parent_company: "TheGlobe.com Inc.",
    country: "United States",
    peak_users: "20 Million Users"
  },
  {
    name: "SixDegrees.com",
    slug: "sixdegrees",
    domain: "sixdegrees.com",
    category: "Social",
    status: "CONFIRMED_DEAD",
    founded_year: 1997,
    death_year: 2000,
    cause_category: "Technological Obsolescence",
    tagline: "The very first real social network based on the six degrees of separation theory.",
    description: "Launched in 1997 by Andrew Weinreich, SixDegrees.com is widely recognized by historians as the very first true social networking website, allowing users to create profiles, list friends, and surf friends' networks. Youth Internet Corp acquired it for $125 million in 1999 and shut it down in December 2000 because people lacked digital cameras and photo uploads.",
    cause_summary: "Launched a decade ahead of its time; users had few digital contacts online and no digital camera photos to share.",
    final_moments: "Closed on December 30, 2000. Founder Andrew Weinreich later observed: 'The internet wasn't ready yet.'",
    parent_company: "YouthStream Media Networks",
    country: "United States",
    peak_users: "3.5 Million Registered Members"
  },
  {
    name: "Tripod.com Classic",
    slug: "tripod-classic",
    domain: "tripod.com",
    category: "Communities",
    status: "ZOMBIE",
    founded_year: 1992,
    death_year: 2005,
    cause_category: "Acquired & Discontinued",
    tagline: "The college homepage builder that invented the popup ad.",
    description: "Founded by Bo Peabody and Brett Hersh in 1992, Tripod provided free web hosting, homepages, and resume builders to college students. In 1997, Tripod engineer Ethan Zuckerman wrote code to launch an advertisement in a separate window to avoid associating a major car brand with adult content—accidentally inventing the popup ad.",
    cause_summary: "Lycos acquired Tripod for $58M; over-commercialization, popup ads, and the rise of MySpace and Blogger eroded its community.",
    final_moments: "Tripod was degraded into a stripped-down ad-laden paid hosting service.",
    parent_company: "Lycos",
    country: "United States",
    peak_users: "18 Million Personal Pages"
  },
  {
    name: "Angelfire Classic",
    slug: "angelfire-classic",
    domain: "angelfire.com",
    category: "Communities",
    status: "ZOMBIE",
    founded_year: 1996,
    death_year: 2005,
    cause_category: "Acquired & Discontinued",
    tagline: "The HTML playground for millions of late-90s teenage homepages.",
    description: "Founded in 1996 by Mark Dyne, Angelfire offered free web space and simple HTML editing tools. Alongside GeoCities and Tripod, it formed the triumvirate of Web 1.0 free homepage hosting. Acquired by Lycos in 1998, it became synonymous with MIDIs, animated construction GIFs, and web rings.",
    cause_summary: "Absorbed into Lycos; social networks like MySpace and Facebook made personal HTML homepage builders obsolete.",
    final_moments: "Continued running as a legacy paid host with retro branding.",
    parent_company: "Lycos",
    country: "United States",
    peak_users: "14 Million Homepages"
  },
  {
    name: "Xoom.com",
    slug: "xoom-homepages",
    domain: "xoom.com",
    category: "Communities",
    status: "CONFIRMED_DEAD",
    founded_year: 1996,
    death_year: 1999,
    cause_category: "Acquired & Discontinued",
    tagline: "Unlimited free homepage hosting and clipart galleries in the late 90s.",
    description: "Xoom.com was a wildly popular late-90s web hosting community that offered unlimited web space, free email, and downloadable clipart software. NBC acquired Xoom in 1999 to merge into NBCi (NBC Internet), which collapsed in the dot-com crash.",
    cause_summary: "Merged into NBCi; NBC wrote off hundreds of millions and dismantled the community.",
    final_moments: "Folded into NBCi in 1999; the Xoom name was later repurposed by PayPal for money transfers.",
    parent_company: "NBC / General Electric",
    country: "United States",
    peak_users: "12 Million Members"
  },
  {
    name: "FortuneCity",
    slug: "fortunecity",
    domain: "fortunecity.com",
    category: "Communities",
    status: "CONFIRMED_DEAD",
    founded_year: 1997,
    death_year: 2012,
    cause_category: "Bankruptcy",
    tagline: "The European GeoCities organized into virtual cyber-neighborhoods.",
    description: "FortuneCity was founded in London in 1997 by Richard Northcott and Marco Rizzuto. Like GeoCities, it organized users' free personal homepages into thematic virtual cities like 'SiliconValley' and 'SouthBeach'. It was listed on the Frankfurt Stock Exchange in 1999 with a multi-hundred-million-dollar valuation before traffic collapsed.",
    cause_summary: "Failed transition from free personal pages to modern CMS platforms; server disk failure in 2012 finalized its shutdown.",
    final_moments: "In April 2012, a catastrophic storage server collapse caused FortuneCity to permanently take all user pages offline.",
    parent_company: "FortuneCity plc",
    country: "United Kingdom",
    peak_users: "20 Million Registered Citizens"
  },
  {
    name: "Bolt.com",
    slug: "bolt-com",
    domain: "bolt.com",
    category: "Social",
    status: "CONFIRMED_DEAD",
    founded_year: 1996,
    death_year: 2007,
    cause_category: "Legal & Regulatory",
    tagline: "The beloved late-90s teenage social network with message boards and webcams.",
    description: "Bolt.com was founded in 1996 by Dan Pelson and Jane Mount as a dedicated teenage hangout featuring message boards, poetry clubs, and horoscopes. At its peak, it claimed millions of daily teen users. In 2006, it attempted to pivot into video sharing, leading to copyright lawsuits from Universal Music Group that bankrupted the company.",
    cause_summary: "Copyright infringement lawsuits from Universal Music Group over user video uploads destroyed its remaining cash.",
    final_moments: "Filed Chapter 11 bankruptcy in February 2007 following UMG's multi-million dollar lawsuit.",
    parent_company: "Bolt Inc.",
    country: "United States",
    peak_users: "4 Million Teenage Members"
  },
  {
    name: "PointCast Network",
    slug: "pointcast",
    domain: "pointcast.com",
    category: "Web technology",
    status: "CONFIRMED_DEAD",
    founded_year: 1996,
    death_year: 2000,
    cause_category: "Market Competition",
    tagline: "The screensaver 'push technology' pioneer that crippled corporate networks across America.",
    description: "PointCast was the sensation of 1996: a dynamic screensaver that continuously fetched and displayed real-time news, stock quotes, and weather. In 1997, Rupert Murdoch's News Corp offered $450 million to acquire PointCast, which CEO Christopher Hassett rejected. Its bandwidth-heavy push packets overwhelmed corporate LANs, leading IT managers to ban it.",
    cause_summary: "Network administrators banned its packet-heavy traffic; rejected $450M buyout from News Corp; sold for $7M in 1999.",
    final_moments: "Sold off in 1999 for just $7 million to Idealab's Launchpad, before disappearing in 2000.",
    parent_company: "PointCast Inc.",
    country: "United States",
    peak_users: "1.5 Million Daily Active Professionals"
  },
  {
    name: "Broadcast.com",
    slug: "broadcast-com",
    domain: "broadcast.com",
    category: "Streaming",
    status: "CONFIRMED_DEAD",
    founded_year: 1995,
    death_year: 2002,
    cause_category: "Acquired & Discontinued",
    tagline: "The early internet radio pioneer that made Mark Cuban a billionaire when Yahoo bought it for $5.7 billion.",
    description: "Originally founded in 1995 as AudioNet by Mark Cuban and Todd Wagner to listen to Indiana Hoosiers basketball games, it became Broadcast.com. In April 1999, Yahoo acquired Broadcast.com for $5.7 billion in stock—one of the most overvalued dot-com acquisitions in history. Yahoo subsequently dismantled it.",
    cause_summary: "Peak dot-com acquisition bubble; Yahoo failed to monetize streaming audio and shuttered the service.",
    final_moments: "Yahoo split Broadcast.com into Yahoo! Platinum and Yahoo! Podcasts, which were both cancelled soon after.",
    parent_company: "Yahoo!",
    country: "United States",
    peak_users: "570,000 Live Broadcast Listeners"
  },
  // --- GOOGLE GRAVEYARD EXPANSIONS ---
  {
    name: "Google Reader",
    slug: "google-reader",
    domain: "google.com/reader",
    category: "Communities",
    status: "CONFIRMED_DEAD",
    founded_year: 2005,
    death_year: 2013,
    cause_category: "Strategic Pivot",
    tagline: "The RSS news aggregator whose 2013 execution sparked grief across the open web.",
    description: "Google Reader was launched in October 2005 by Google engineer Chris Wetherell as an RSS/Atom aggregator. It grew a passionate community of journalists, developers, and knowledge workers who shared and commented on articles. On March 13, 2013, Google announced its shutdown in a 'spring cleaning' push to focus on Google+.",
    cause_summary: "Google pivoted executive focus and engineering resources to force-feed Google+; RSS was viewed as an ad-unfriendly open protocol.",
    final_moments: "On July 1, 2013, Google pulled the master switch. A black banner informed millions of power users that their feeds were gone.",
    parent_company: "Google",
    country: "United States",
    peak_users: "30 Million RSS Enthusiasts"
  },
  {
    name: "Google Wave",
    slug: "google-wave",
    domain: "wave.google.com",
    category: "Developer tools",
    status: "CONFIRMED_DEAD",
    founded_year: 2009,
    death_year: 2012,
    cause_category: "Lack of Monetization",
    tagline: "The hyper-ambitious real-time collaborative workspace that arrived a decade before Slack and Figma.",
    description: "Created by Google Maps inventors Lars and Jens Rasmussen, Google Wave merged email, instant messaging, wikis, and document collaboration into a live canvas where users could see each other typing letter-by-letter in real time. Despite intense developer hype and invite scarcity, users found it overwhelming.",
    cause_summary: "Extreme complexity, steep learning curve, and lack of clear consumer use cases; open-sourced to Apache Wave and forgotten.",
    final_moments: "Development ceased in August 2010; servers powered off in April 2012.",
    parent_company: "Google",
    country: "Australia / United States",
    peak_users: "1 Million Invite Holders"
  },
  {
    name: "Google Buzz",
    slug: "google-buzz",
    domain: "buzz.google.com",
    category: "Social",
    status: "CONFIRMED_DEAD",
    founded_year: 2010,
    death_year: 2011,
    cause_category: "Security & Privacy",
    tagline: "Google's ill-fated social network that automatically exposed users' Gmail contact lists to the public.",
    description: "Google Buzz launched in February 2010 as a social microblogging layer integrated directly inside Gmail. It provoked immediate global outrage when it automatically published users' most frequent email and chat contacts as public followers, exposing domestic abuse victims, journalists' sources, and business rivals.",
    cause_summary: "Massive privacy crisis and FTC consent decree triggered by auto-subscribing users' private Gmail contacts to public followers.",
    final_moments: "Killed in October 2011 in favor of Google+ after paying an $8.5 million class-action settlement.",
    parent_company: "Google",
    country: "United States",
    peak_users: "Dozens of millions of Gmail inboxes"
  },
  {
    name: "Google+",
    slug: "google-plus",
    domain: "plus.google.com",
    category: "Social",
    status: "CONFIRMED_DEAD",
    founded_year: 2011,
    death_year: 2019,
    cause_category: "Security & Privacy",
    tagline: "Google's multi-billion-dollar Facebook killer that forced YouTube commenters to use real names.",
    description: "Google+ launched in June 2011 under Vic Gundotra as an existential company-wide effort to challenge Facebook, featuring Circles, Hangouts, and Sparks. Google forcibly tied Google+ to YouTube comments, Play Store reviews, and Gmail accounts. In 2018, the discovery of API data leaks exposing 500,000 users prompted its shutdown.",
    cause_summary: "Low organic engagement ('ghost town'), backlash against mandatory integration into YouTube, and two severe API security breaches.",
    final_moments: "Consumer service shut down permanently on April 2, 2019; all user photos and communities were deleted.",
    parent_company: "Google",
    country: "United States",
    peak_users: "540 Million Active Across Ecosystem"
  },
  {
    name: "Google Answers",
    slug: "google-answers",
    domain: "answers.google.com",
    category: "Search",
    status: "CONFIRMED_DEAD",
    founded_year: 2002,
    death_year: 2006,
    cause_category: "Market Competition",
    tagline: "The paid knowledge market where researchers answered inquiries for bounties from $2 to $200.",
    description: "Launched in April 2002, Google Answers allowed users to post complex questions and offer a monetary bounty ranging from $2 to $200. Over 800 certified freelance researchers answered queries. It struggled to scale against free community alternatives like Yahoo! Answers and Wikipedia.",
    cause_summary: "Free community question-and-answer websites (Yahoo! Answers) overwhelmed its paid researcher model.",
    final_moments: "Stopped accepting new questions in November 2006; archives remained readable for several years.",
    parent_company: "Google",
    country: "United States",
    peak_users: "100,000 Paid Submissions"
  },
  {
    name: "Google Talk (Gchat)",
    slug: "google-talk",
    domain: "google.com/talk",
    category: "Messaging",
    status: "CONFIRMED_DEAD",
    founded_year: 2005,
    death_year: 2017,
    cause_category: "Strategic Pivot",
    tagline: "The beloved, lightning-fast XMPP instant messenger embedded in Gmail's sidebar.",
    description: "Google Talk launched in August 2005 as a lightweight desktop chat client and Gmail sidebar gadget based on the open XMPP (Jabber) protocol. Known affectionate as 'Gchat', it became the communication backbone of millions of offices, college dorms, and remote workers before Google replaced it with Hangouts.",
    cause_summary: "Replaced by Google Hangouts as Google abandoned open federated XMPP in favor of proprietary messaging silos.",
    final_moments: "Replaced in Gmail by Hangouts in 2013; the third-party XMPP server access was terminated in 2017.",
    parent_company: "Google",
    country: "United States",
    peak_users: "70 Million Gchatters"
  },
  {
    name: "Google Hangouts",
    slug: "google-hangouts",
    domain: "hangouts.google.com",
    category: "Messaging",
    status: "CONFIRMED_DEAD",
    founded_year: 2013,
    death_year: 2022,
    cause_category: "Strategic Pivot",
    tagline: "The video group chat pioneer replaced by the splintered Google Meet and Google Chat.",
    description: "Launched at Google I/O 2013, Hangouts unified Google Talk, Google+ Messenger, and Google+ Hangouts into one cross-platform app. It popularized free 10-person group video calls. Over nine years, Google fragmented its communication strategy into Duo, Allo, Meet, and Chat.",
    cause_summary: "Fragmented by Google's confusing messaging reorganization into Google Meet and Google Chat.",
    final_moments: "Shut down officially in November 2022, with all remaining web users redirected to Google Chat.",
    parent_company: "Google",
    country: "United States",
    peak_users: "1 Billion Play Store Downloads"
  },
  {
    name: "Google Allo",
    slug: "google-allo",
    domain: "allo.google.com",
    category: "Messaging",
    status: "CONFIRMED_DEAD",
    founded_year: 2016,
    death_year: 2019,
    cause_category: "Lack of Monetization",
    tagline: "The AI assistant chat app with Smart Reply that refused to support SMS.",
    description: "Unveiled alongside Duo at Google I/O 2016, Allo showcased the brand-new Google Assistant, Whisper/Shout font scaling, and AI Smart Replies. However, it required phone number signups and lacked SMS fallback, failing completely to attract users away from WhatsApp and iMessage.",
    cause_summary: "Lacked SMS fallback, faced entrenched competitors (WhatsApp, iMessage), and failed to generate viral growth.",
    final_moments: "Google ceased investment in April 2018 and pulled the servers on March 12, 2019.",
    parent_company: "Google",
    country: "United States",
    peak_users: "50 Million Downloads"
  },
  {
    name: "Google Code",
    slug: "google-code",
    domain: "code.google.com",
    category: "Developer tools",
    status: "CONFIRMED_DEAD",
    founded_year: 2006,
    death_year: 2016,
    cause_category: "Market Competition",
    tagline: "Google's free Subversion, Mercurial, and Git open-source hosting repository.",
    description: "Google Code provided free source code hosting, bug tracking, and release binaries for open-source projects using Subversion and Mercurial. In the early 2010s, developers migrated en masse to GitHub's Git-native pull request workflow. Google conceded defeat in 2015.",
    cause_summary: "Complete developer migration to GitHub; Google officially recognized GitHub had won the open-source hosting battle.",
    final_moments: "Read-only mode instituted in August 2015; closed completely in January 2016 with an export tool to GitHub.",
    parent_company: "Google",
    country: "United States",
    peak_users: "350,000 Open Source Projects"
  },
  {
    name: "Google URL Shortener (goo.gl)",
    slug: "googl-shortener",
    domain: "goo.gl",
    category: "Web technology",
    status: "CONFIRMED_DEAD",
    founded_year: 2009,
    death_year: 2019,
    cause_category: "Technological Obsolescence",
    tagline: "The fastest, most secure URL shortener with built-in spam protection and QR codes.",
    description: "Launched in December 2009, goo.gl allowed users to generate concise redirect links with real-time click analytics and QR codes. In March 2018, Google announced its sunset in favor of Firebase Dynamic Links, disabling new link creation in 2019.",
    cause_summary: "Modern web APIs shifted toward deep-linking and Firebase Dynamic Links; URL shortening was commoditized.",
    final_moments: "New link creation terminated on March 30, 2019.",
    parent_company: "Google",
    country: "United States",
    peak_users: "Billions of redirected clicks"
  },
  {
    name: "Google Cloud Print",
    slug: "google-cloud-print",
    domain: "cloudprint.google.com",
    category: "Developer tools",
    status: "CONFIRMED_DEAD",
    founded_year: 2010,
    death_year: 2020,
    cause_category: "Technological Obsolescence",
    tagline: "The cloud bridge that allowed ChromeOS laptops to print over the internet.",
    description: "Created in 2010 to solve ChromeOS's lack of local hardware printer drivers, Cloud Print routed print jobs from any web browser or phone to internet-connected printers. As ChromeOS gained native CUPS network printing, Cloud Print became redundant.",
    cause_summary: "Native network printing (CUPS/IPP) matured in ChromeOS, eliminating the need for cloud-mediated print queues.",
    final_moments: "Shut down on December 31, 2020. Google advised users to transition to native local print protocols.",
    parent_company: "Google",
    country: "United States",
    peak_users: "Millions of Chromebook Classrooms"
  },
  {
    name: "Google Play Music",
    slug: "google-play-music",
    domain: "music.google.com",
    category: "Streaming",
    status: "CONFIRMED_DEAD",
    founded_year: 2011,
    death_year: 2020,
    cause_category: "Strategic Pivot",
    tagline: "The beloved cloud music locker that let you upload 50,000 MP3s for free.",
    description: "Google Play Music (originally Google Music Beta) launched in 2011. Its standout feature was a free cloud locker allowing users to upload 50,000 personal MP3s and stream them on any phone. Google forced all users to migrate to YouTube Music in late 2020.",
    cause_summary: "Consolidated all Google music operations under the YouTube Music brand.",
    final_moments: "Service stopped functioning in December 2020, and all cloud music locker files were purged in February 2021.",
    parent_company: "Google",
    country: "United States",
    peak_users: "15 Million Subscribers"
  },
  {
    name: "Inbox by Gmail",
    slug: "inbox-by-gmail",
    domain: "inbox.google.com",
    category: "Developer tools",
    status: "CONFIRMED_DEAD",
    founded_year: 2014,
    death_year: 2019,
    cause_category: "Strategic Pivot",
    tagline: "The experimental email client with snoozing, trip bundles, and zero-inbox philosophy.",
    description: "Created by the Gmail team in October 2014, Inbox revolutionized email workflows with smart bundling, snoozing emails to specific times, reminders, and Highlights. Despite intense user love, Google cancelled it in April 2019 while porting select features to standard Gmail.",
    cause_summary: "Maintaining two separate web email clients was deemed inefficient; key features merged into Gmail.",
    final_moments: "App and web portal shut down on April 2, 2019, to widespread mourning from productivity power users.",
    parent_company: "Google",
    country: "United States",
    peak_users: "10 Million Loyal Inbox Zero Users"
  },
  {
    name: "Picasa & Picasa Web Albums",
    slug: "picasa",
    domain: "picasaweb.google.com",
    category: "Communities",
    status: "CONFIRMED_DEAD",
    founded_year: 2002,
    death_year: 2016,
    cause_category: "Strategic Pivot",
    tagline: "The rapid local photo organizer and cloud album gallery.",
    description: "Founded by Idealab and acquired by Google in 2004, Picasa was celebrated for its blazingly fast facial recognition and simple desktop photo editing. In 2016, Google retired Picasa in favor of Google Photos.",
    cause_summary: "Google Photos launch in 2015 rendered Picasa's separate desktop/cloud brand redundant.",
    final_moments: "Picasa Web Albums retired in May 2016; desktop app downloads and updates ceased in March 2016.",
    parent_company: "Google",
    country: "United States",
    peak_users: "25 Million Active Photographers"
  },
  {
    name: "Songza",
    slug: "songza",
    domain: "songza.com",
    category: "Streaming",
    status: "CONFIRMED_DEAD",
    founded_year: 2007,
    death_year: 2016,
    cause_category: "Acquired & Discontinued",
    tagline: "The concierge playlist streamer that knew what you were doing on a rainy Tuesday morning.",
    description: "Songza pioneered situational playlists using a 'Music Concierge' that curated songs based on time of day, mood, and activity (e.g. 'Coding at 2 AM', 'Waking Up Gently'). Google acquired Songza in 2014 for $39M and absorbed its playlist algorithms into Google Play Music before shutting it down in 2016.",
    cause_summary: "Acquired by Google to harvest its human-curated situational playlist recommendation algorithms.",
    final_moments: "On January 31, 2016, Songza stopped streaming and redirected all accounts to Google Play Music.",
    parent_company: "Google",
    country: "United States",
    peak_users: "5.5 Million Monthly Streamers"
  },
  {
    name: "Bump (App)",
    slug: "bump-app",
    domain: "bu.mp",
    category: "Mobile",
    status: "CONFIRMED_DEAD",
    founded_year: 2008,
    death_year: 2014,
    cause_category: "Acquired & Discontinued",
    tagline: "Physically bumping two smartphones together to share contacts and photos.",
    description: "Bump allowed two smartphone users to physically bump their hands together to exchange contacts and files using accelerometer timestamps matched on cloud servers. Downloaded over 100 million times, Google acquired Bump Technologies in September 2013 and discontinued it months later.",
    cause_summary: "Acquired by Google for engineering talent; Google shut down the app to focus the team on Google Photos.",
    final_moments: "Removed from App Store and Google Play on January 31, 2014; backend servers wiped.",
    parent_company: "Google",
    country: "United States",
    peak_users: "125 Million Downloads"
  },
  {
    name: "Google Stadia",
    slug: "google-stadia",
    domain: "stadia.google.com",
    category: "Gaming",
    status: "CONFIRMED_DEAD",
    founded_year: 2019,
    death_year: 2023,
    cause_category: "Lack of Monetization",
    tagline: "Google's 4K cloud gaming platform that required full retail game purchases.",
    description: "Announced by Phil Harrison at GDC 2019 as a revolution that would surpass PlayStation and Xbox by streaming games straight from YouTube without a console. Its flawed business model required gamers to purchase games at full $60 retail price on top of a monthly subscription.",
    cause_summary: "Flawed retail pricing, shuttering of first-party studios in 2021, and low subscriber numbers against Xbox Cloud Gaming.",
    final_moments: "Servers powered down on January 18, 2023. Google refunded 100% of all hardware and software purchases.",
    parent_company: "Google",
    country: "United States",
    peak_users: "750,000 Active Players"
  },
  {
    name: "Google Jamboard",
    slug: "google-jamboard",
    domain: "jamboard.google.com",
    category: "Developer tools",
    status: "CONFIRMED_DEAD",
    founded_year: 2016,
    death_year: 2024,
    cause_category: "Strategic Pivot",
    tagline: "The collaborative digital whiteboard for schools and remote teams.",
    description: "Google Jamboard was a cloud-based collaborative digital whiteboard app and a companion $5,000 55-inch 4K touchscreen display. Widely used in remote classrooms during the pandemic, Google announced in late 2023 that it would shut down Jamboard and partner with FigJam, Miro, and Lucidspark.",
    cause_summary: "Google pivoted away from standalone whiteboard apps to integrate third-party partners (Figma/FigJam and Miro).",
    final_moments: "On October 1, 2024, Jamboard went into view-only mode, and all Jam files were deleted on December 31, 2024.",
    parent_company: "Google",
    country: "United States",
    peak_users: "Millions of Classrooms and Teams"
  },
  {
    name: "Google Domains",
    slug: "google-domains",
    domain: "domains.google.com",
    category: "Developer tools",
    status: "CONFIRMED_DEAD",
    founded_year: 2014,
    death_year: 2023,
    cause_category: "Strategic Pivot",
    tagline: "The clean, honest, zero-upsell domain registrar beloved by developers.",
    description: "Launched in 2014, Google Domains became one of the web's most popular domain registrars due to its clean UI, free WHOIS privacy, and refusal to bombard users with GoDaddy-style predatory upsells. In June 2023, Google stunned developers by announcing it was selling all assets to Squarespace for $180M.",
    cause_summary: "Sold to Squarespace for $180M as Google cut non-core product divisions to focus on generative AI.",
    final_moments: "On September 7, 2023, the sale to Squarespace closed, migrating 10+ million domains off Google infrastructure.",
    parent_company: "Google",
    country: "United States",
    peak_users: "10 Million Registered Domains"
  },
  {
    name: "Google Podcasts",
    slug: "google-podcasts",
    domain: "podcasts.google.com",
    category: "Streaming",
    status: "CONFIRMED_DEAD",
    founded_year: 2018,
    death_year: 2024,
    cause_category: "Strategic Pivot",
    tagline: "The minimalist, clean RSS podcast player for Android and the web.",
    description: "Google Podcasts launched in 2018 as a lightweight, ad-free podcast app integrated with Google Search and Google Assistant. In late 2023, Google announced it was killing the app to force all podcast listening into YouTube Music.",
    cause_summary: "Consolidated all audio listening under YouTube Music to monetize podcasts via YouTube video ads and subscriptions.",
    final_moments: "US operations ceased in April 2024, and global operations concluded in June 2024.",
    parent_company: "Google",
    country: "United States",
    peak_users: "500 Million Play Store Downloads"
  }
];
